export const FETCH_FEATURED_COLLECTIONS = 'FETCH_FEATURED_COLLECTIONS'
export const FETCH_FEATURED_COLLECTIONS_SUCCESS = 'FETCH_FEATURED_COLLECTIONS_SUCCESS'
export const FETCH_FEATURED_COLLECTIONS_FAIL = 'FETCH_FEATURED_COLLECTIONS_FAIL'

export const FETCH_ALL_COLLECTIONS = 'FETCH_ALL_COLLECTIONS'
export const FETCH_ALL_COLLECTIONS_SUCCESS = 'FETCH_ALL_COLLECTIONS_SUCCESS'
export const FETCH_ALL_COLLECTIONS_FAIL = 'FETCH_ALL_COLLECTIONS_FAIL'

export const FETCH_FOLLOWING_COLLECTIONS = 'FETCH_FOLLOWING_COLLECTIONS'
export const FETCH_FOLLOWING_COLLECTIONS_SUCCESS = 'FETCH_FOLLOWING_COLLECTIONS_SUCCESS'
export const FETCH_FOLLOWING_COLLECTIONS_FAIL = 'FETCH_FOLLOWING_COLLECTIONS_FAIL'

export const FETCH_MY_COLLECTIONS = 'FETCH_MY_COLLECTIONS'
export const FETCH_MY_COLLECTIONS_SUCCESS = 'FETCH_MY_COLLECTIONS_SUCCESS'
export const FETCH_MY_COLLECTIONS_FAIL = 'FETCH_MY_COLLECTIONS_FAIL'

export const FETCH_THE_COLLECTION = 'FETCH_THE_COLLECTION'
export const FETCH_THE_COLLECTION_SUCCESS = 'FETCH_THE_COLLECTION_SUCCESS'
export const FETCH_THE_COLLECTION_FAIL = 'FETCH_THE_COLLECTION_FAIL'
