// history
export const ADD_HISTORY = 'ADD_HISTORY'

// search
export const FETCH_SEARCH_RESULTS = 'FETCH_SEARCH_RESULTS'
export const FETCH_SEARCH_RESULTS_SUCCESS = 'FETCH_SEARCH_RESULTS_SUCCESS'
export const FETCH_SEARCH_RESULTS_FAIL = 'FETCH_SEARCH_RESULTS_FAIL'
export const CLEAN_SEARCH_SHARE_RESULTS = 'CLEAN_SEARCH_SHARE_RESULTS'

// article
export const FETCH_ARTICLE = 'FETCH_ARTICLE'
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS'
export const FETCH_ARTICLE_FAIL = 'FETCH_ARTICLE_FAIL'
