export const FETCH_FEATURED_POSTS = 'FETCH_FEATURED_POSTS'
export const FETCH_FEATURED_POSTS_SUCCESS = 'FETCH_FEATURED_POSTS_SUCCESS'
export const FETCH_FEATURED_POSTS_FAIL = 'FETCH_FEATURED_POSTS_FAIL'
