export const FETCH_FEATURED_POSTS = 'FETCH_FEATURED_POSTS'
export const FETCH_FEATURED_POSTS_SUCCESS = 'FETCH_FEATURED_POSTS_SUCCESS'
export const FETCH_FEATURED_POSTS_FAIL = 'FETCH_FEATURED_POSTS_FAIL'

export const FETCH_HOME_POPULAR_POSTS = 'FETCH_HOME_POPULAR_POSTS'
export const FETCH_HOME_POPULAR_POSTS_SUCCESS = 'FETCH_HOME_POPULAR_POSTS_SUCCESS'
export const FETCH_HOME_POPULAR_POSTS_FAIL = 'FETCH_HOME_POPULAR_POSTS_FAIL'

export const FETCH_LATEST_POSTS = 'FETCH_LATEST_POSTS'
export const FETCH_LATEST_POSTS_SUCCESS = 'FETCH_LATEST_POSTS_SUCCESS'
export const FETCH_LATEST_POSTS_FAIL = 'FETCH_LATEST_POSTS_FAIL'

export const FETCH_RANDOM_POSTS = 'FETCH_RANDOM_POSTS'
export const FETCH_RANDOM_POSTS_SUCCESS = 'FETCH_RANDOM_POSTS_SUCCESS'
export const FETCH_RANDOM_POSTS_FAIL = 'FETCH_RANDOM_POSTS_FAIL'

export const FETCH_TAG_POSTS = 'FETCH_TAG_POSTS'
export const FETCH_TAG_POSTS_SUCCESS = 'FETCH_TAG_POSTS_SUCCESS'
export const FETCH_TAG_POSTS_FAIL = 'FETCH_TAG_POSTS_FAIL'

export const FETCH_COLLECTION_POSTS = 'FETCH_COLLECTION_POSTS'
export const FETCH_COLLECTION_POSTS_SUCCESS = 'FETCH_COLLECTION_POSTS_SUCCESS'
export const FETCH_COLLECTION_POSTS_FAIL = 'FETCH_COLLECTION_POSTS_FAIL'

export const FETCH_SHARE_LIST = 'FETCH_SHARE_LIST'
export const FETCH_SHARE_LIST_SUCCESS = 'FETCH_SHARE_LIST_SUCCESS'
export const FETCH_SHARE_LIST_FAIL = 'FETCH_SHARE_LIST_FAIL'

export const FETCH_RANDOM_SHARES = 'FETCH_RANDOM_SHARES'
export const FETCH_RANDOM_SHARES_SUCCESS = 'FETCH_RANDOM_SHARES_SUCCESS'
export const FETCH_RANDOM_SHARES_FAIL = 'FETCH_RANDOM_SHARES_FAIL'

export const FETCH_RANDOM_GALLERIES = 'FETCH_RANDOM_GALLERIES'
export const FETCH_RANDOM_GALLERIES_SUCCESS = 'FETCH_RANDOM_GALLERIES_SUCCESS'
export const FETCH_RANDOM_GALLERIES_FAIL = 'FETCH_RANDOM_GALLERIES_FAIL'
