export const FETCH_FEATURED_POSTS = 'FETCH_FEATURED_POSTS'
export const FETCH_FEATURED_POSTS_SUCCESS = 'FETCH_FEATURED_POSTS_SUCCESS'
export const FETCH_FEATURED_POSTS_FAIL = 'FETCH_FEATURED_POSTS_FAIL'

export const FETCH_HOME_POPULAR_POSTS = 'FETCH_HOME_POPULAR_POSTS'
export const FETCH_HOME_POPULAR_POSTS_SUCCESS = 'FETCH_HOME_POPULAR_POSTS_SUCCESS'
export const FETCH_HOME_POPULAR_POSTS_FAIL = 'FETCH_HOME_POPULAR_POSTS_FAIL'
