export const FETCH_TOP_TAGS = 'FETCH_TOP_TAGS'
export const FETCH_TOP_TAGS_SUCCESS = 'FETCH_TOP_TAGS_SUCCESS'
export const FETCH_TOP_TAGS_FAIL = 'FETCH_TOP_TAGS_FAIL'

export const FETCH_ALL_TAGS = 'FETCH_ALL_TAGS'
export const FETCH_ALL_TAGS_SUCCESS = 'FETCH_ALL_TAGS_SUCCESS'
export const FETCH_ALL_TAGS_FAIL = 'FETCH_ALL_TAGS_FAIL'
