export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'
export const DELETE_ACCESS_TOKEN = 'DELETE_ACCESS_TOKEN'

export const SET_USER = 'SET_USER'
export const SIGN_OUT = 'SIGN_OUT'

export const FETCH_AUTHOR = 'FETCH_AUTHOR'
export const FETCH_AUTHOR_SUCCESS = 'FETCH_AUTHOR_SUCCESS'
export const FETCH_AUTHOR_FAIL = 'FETCH_AUTHOR_FAIL'

export const FETCH_AUTHOR_POSTS = 'FETCH_AUTHOR_POSTS'
export const FETCH_AUTHOR_POSTS_SUCCESS = 'FETCH_AUTHOR_POSTS_SUCCESS'
export const FETCH_AUTHOR_POSTS_FAIL = 'FETCH_AUTHOR_POSTS_FAIL'
export const CLEAN_AUTHOR_POSTS = 'CLEAN_AUTHOR_POSTS'

export const FETCH_AUTHOR_SHARE = 'FETCH_AUTHOR_SHARE'
export const FETCH_AUTHOR_SHARE_SUCCESS = 'FETCH_AUTHOR_SHARE_SUCCESS'
export const FETCH_AUTHOR_SHARE_FAIL = 'FETCH_AUTHOR_SHARE_FAIL'
export const CLEAN_AUTHOR_SHARE = 'CLEAN_AUTHOR_SHARE'

export const FETCH_AUTHOR_LIKES = 'FETCH_AUTHOR_LIKES'
export const FETCH_AUTHOR_LIKES_SUCCESS = 'FETCH_AUTHOR_LIKES_SUCCESS'
export const FETCH_AUTHOR_LIKES_FAIL = 'FETCH_AUTHOR_LIKES_FAIL'
export const CLEAN_AUTHOR_LIKES = 'CLEAN_AUTHOR_LIKES'

export const FETCH_AUTHOR_COLLECTIONS = 'FETCH_AUTHOR_COLLECTIONS'
export const FETCH_AUTHOR_COLLECTIONS_SUCCESS = 'FETCH_AUTHOR_COLLECTIONS_SUCCESS'
export const FETCH_AUTHOR_COLLECTIONS_FAIL = 'FETCH_AUTHOR_COLLECTIONS_FAIL'

export const FETCH_AUTHOR_FOLLOWERS = 'FETCH_AUTHOR_FOLLOWERS'
export const FETCH_AUTHOR_FOLLOWERS_SUCCESS = 'FETCH_AUTHOR_FOLLOWERS_SUCCESS'
export const FETCH_AUTHOR_FOLLOWERS_FAIL = 'FETCH_AUTHOR_FOLLOWERS_FAIL'
export const CLEAN_AUTHOR_FOLLOWERS = 'CLEAN_AUTHOR_FOLLOWERS'

export const FETCH_AUTHOR_FOLLOWING = 'FETCH_AUTHOR_FOLLOWING'
export const FETCH_AUTHOR_FOLLOWING_SUCCESS = 'FETCH_AUTHOR_FOLLOWING_SUCCESS'
export const FETCH_AUTHOR_FOLLOWING_FAIL = 'FETCH_AUTHOR_FOLLOWING_FAIL'
export const CLEAN_AUTHOR_FOLLOWING = 'CLEAN_AUTHOR_FOLLOWING'
